package com.dws.ActualRetro;

public enum VDGenre {
    ACTION, ADVENTURE, CASUAL, FIGHTING, FPS, METROIDVANIA, MMORPG, OPENWORLD, PARTY, PLATFORMS, PUZZLES,
    RACING, RHYTHM, ROGUELIKE, ROGUELITE, SANDBOX, SIMULATION, SOULSLIKE, SPORTS, STRATEGY, SURVIVALHORROR,
    TACTICALRPG, TURNBASEDRPG, VISUALNOVEL


}

